import { Project, PagePlan, PageBrief, GeneratedPage, QAReport, DeploymentLog } from '@/types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    business_name: 'Party Perfect Rentals',
    industry: 'party_rentals',
    primary_locale: 'en-US',
    secondary_locales: ['es-419' as never],
    country: 'US',
    status: 'deployed',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T14:30:00Z',
    page_count: 48,
  },
  {
    id: '2',
    business_name: 'Green Thumb Landscaping',
    industry: 'landscaping',
    primary_locale: 'en-US',
    secondary_locales: [],
    country: 'US',
    status: 'generating',
    created_at: '2024-01-18T09:00:00Z',
    updated_at: '2024-01-22T11:00:00Z',
    page_count: 32,
  },
  {
    id: '3',
    business_name: 'CleanPro Services',
    industry: 'cleaning_services',
    primary_locale: 'nl-BE',
    secondary_locales: ['fr-BE', 'de-BE'],
    country: 'BE',
    status: 'qa_complete',
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-21T16:00:00Z',
    page_count: 96,
  },
  {
    id: '4',
    business_name: 'RoofRight Solutions',
    industry: 'roofing',
    primary_locale: 'en-GB',
    secondary_locales: [],
    country: 'GB',
    status: 'draft',
    created_at: '2024-01-22T13:00:00Z',
    updated_at: '2024-01-22T13:00:00Z',
    page_count: 0,
  },
  {
    id: '5',
    business_name: 'BinBusters Dumpsters',
    industry: 'dumpster_rentals',
    primary_locale: 'en-US',
    secondary_locales: [],
    country: 'US',
    status: 'deployed',
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-01-19T09:00:00Z',
    page_count: 24,
  },
];

export const MOCK_SITEMAP: PagePlan[] = [
  {
    id: 'p1',
    project_id: '1',
    page_type: 'homepage',
    locale: 'en-US',
    slug: '/',
    h1: 'Premium Party Rentals in Austin, TX',
    status: 'approved',
  },
  {
    id: 'p2',
    project_id: '1',
    page_type: 'service',
    locale: 'en-US',
    slug: '/services/tent-rentals',
    h1: 'Tent Rentals for Any Occasion',
    status: 'approved',
  },
  {
    id: 'p3',
    project_id: '1',
    page_type: 'service',
    locale: 'en-US',
    slug: '/services/table-chair-rentals',
    h1: 'Table & Chair Rentals',
    status: 'generated',
  },
  {
    id: 'p4',
    project_id: '1',
    page_type: 'location',
    locale: 'en-US',
    slug: '/locations/austin',
    h1: 'Party Rentals in Austin',
    status: 'generated',
  },
  {
    id: 'p5',
    project_id: '1',
    page_type: 'service_location',
    locale: 'en-US',
    slug: '/tent-rentals/austin',
    h1: 'Tent Rentals in Austin, TX',
    status: 'pending',
  },
  {
    id: 'p6',
    project_id: '1',
    page_type: 'service_location',
    locale: 'en-US',
    slug: '/tent-rentals/cedar-park',
    h1: 'Tent Rentals in Cedar Park, TX',
    status: 'pending',
  },
  {
    id: 'p7',
    project_id: '1',
    page_type: 'about',
    locale: 'en-US',
    slug: '/about',
    h1: 'About Party Perfect Rentals',
    status: 'approved',
  },
  {
    id: 'p8',
    project_id: '1',
    page_type: 'faq',
    locale: 'en-US',
    slug: '/faq',
    h1: 'Frequently Asked Questions',
    status: 'generated',
  },
  {
    id: 'p9',
    project_id: '1',
    page_type: 'contact',
    locale: 'en-US',
    slug: '/contact',
    h1: 'Contact Party Perfect Rentals',
    status: 'approved',
  },
];

export const MOCK_BRIEFS: PageBrief[] = [
  {
    id: 'b1',
    project_id: '1',
    page_type: 'homepage',
    locale: 'en-US',
    slug: '/',
    h1: 'Premium Party Rentals in Austin, TX',
    meta_title: 'Party Rentals Austin TX | Tents, Tables & More | Party Perfect',
    meta_description: 'Austin\'s #1 party rental company. Tents, tables, chairs, linens & more. Easy online booking. Serving Austin and surrounding areas. Get a free quote today!',
    primary_keyword: 'party rentals Austin TX',
    secondary_keywords: ['tent rentals Austin', 'table rentals Austin', 'chair rentals Austin'],
    schema_types: ['LocalBusiness', 'WebPage', 'FAQPage'],
    tone: 'neutral',
    word_count_target: 1200,
    status: 'approved',
  },
  {
    id: 'b2',
    project_id: '1',
    page_type: 'service',
    locale: 'en-US',
    slug: '/services/tent-rentals',
    h1: 'Tent Rentals for Any Occasion',
    meta_title: 'Tent Rentals Austin TX | Party Tents & Canopies | Party Perfect',
    meta_description: 'Premium tent rentals for weddings, corporate events & parties in Austin TX. Various sizes available. Free delivery & setup. Book online or call today!',
    primary_keyword: 'tent rentals Austin',
    secondary_keywords: ['party tent rental', 'wedding tent rental Austin', 'canopy rentals'],
    schema_types: ['Service', 'LocalBusiness'],
    tone: 'neutral',
    word_count_target: 1000,
    status: 'approved',
  },
  {
    id: 'b3',
    project_id: '1',
    page_type: 'location',
    locale: 'en-US',
    slug: '/locations/austin',
    h1: 'Party Rentals in Austin',
    meta_title: 'Party Rentals Austin | Local Delivery & Setup | Party Perfect',
    meta_description: 'Looking for party rentals in Austin? Party Perfect delivers tents, tables, chairs & more throughout Austin and surrounding neighborhoods. Same-day quotes!',
    primary_keyword: 'party rentals in Austin',
    secondary_keywords: ['Austin party rental company', 'party supplies Austin TX'],
    schema_types: ['LocalBusiness', 'Place'],
    tone: 'neutral',
    word_count_target: 900,
    status: 'generated',
  },
];

export const MOCK_CONTENT: GeneratedPage[] = [
  {
    id: 'c1',
    project_id: '1',
    brief_id: 'b1',
    slug: '/',
    h1: 'Premium Party Rentals in Austin, TX',
    locale: 'en-US',
    page_type: 'homepage',
    html_content: '<h1>Premium Party Rentals in Austin, TX</h1><p>Welcome to Party Perfect Rentals, Austin\'s premier party rental company. We offer a wide selection of tents, tables, chairs, linens, and more for all your event needs.</p><h2>Our Services</h2><p>From intimate gatherings to large corporate events, we have everything you need to make your event unforgettable.</p>',
    status: 'approved',
    generated_at: '2024-01-18T10:00:00Z',
    approved_at: '2024-01-19T09:00:00Z',
  },
  {
    id: 'c2',
    project_id: '1',
    brief_id: 'b2',
    slug: '/services/tent-rentals',
    h1: 'Tent Rentals for Any Occasion',
    locale: 'en-US',
    page_type: 'service',
    html_content: '<h1>Tent Rentals for Any Occasion</h1><p>Party Perfect offers premium tent rentals for weddings, corporate events, birthday parties, and more in the Austin area.</p>',
    status: 'generated',
    generated_at: '2024-01-18T11:00:00Z',
  },
  {
    id: 'c3',
    project_id: '1',
    brief_id: 'b3',
    slug: '/locations/austin',
    h1: 'Party Rentals in Austin',
    locale: 'en-US',
    page_type: 'location',
    html_content: '<h1>Party Rentals in Austin</h1><p>Serving the Austin metro area with premium party equipment rentals. Fast delivery, professional setup, and competitive pricing.</p>',
    status: 'pending',
    generated_at: undefined,
  },
];

export const MOCK_QA_REPORT: QAReport = {
  project_id: '1',
  run_at: '2024-01-22T14:00:00Z',
  pass_count: 42,
  warning_count: 4,
  fail_count: 2,
  issues: [
    {
      page_slug: '/',
      check_name: 'Meta Title Length',
      status: 'pass',
      message: 'Meta title is 58 characters (optimal: 50-60)',
    },
    {
      page_slug: '/',
      check_name: 'Meta Description Length',
      status: 'pass',
      message: 'Meta description is 142 characters (optimal: 120-160)',
    },
    {
      page_slug: '/services/tent-rentals',
      check_name: 'Word Count',
      status: 'warning',
      message: 'Page content is 850 words, target is 1000 words',
    },
    {
      page_slug: '/locations/austin',
      check_name: 'Schema Markup',
      status: 'fail',
      message: 'Missing required LocalBusiness schema fields: telephone, address',
    },
    {
      page_slug: '/tent-rentals/austin',
      check_name: 'Internal Links',
      status: 'warning',
      message: 'Only 1 internal link found, recommend at least 3',
    },
    {
      page_slug: '/faq',
      check_name: 'FAQPage Schema',
      status: 'fail',
      message: 'FAQPage schema is missing, page type is FAQ but no FAQ schema found',
    },
    {
      page_slug: '/about',
      check_name: 'Word Count',
      status: 'warning',
      message: 'Page content is 720 words, target is 800 words',
    },
    {
      page_slug: '/contact',
      check_name: 'Contact Schema',
      status: 'warning',
      message: 'Consider adding ContactPage schema for better rich results',
    },
  ],
};

export const MOCK_DEPLOY_LOGS: DeploymentLog[] = [
  {
    id: 'l1',
    project_id: '1',
    action: 'Test Connection',
    status: 'success',
    message: 'Successfully connected to WordPress at https://partyperfect.com',
    timestamp: '2024-01-20T09:00:00Z',
  },
  {
    id: 'l2',
    project_id: '1',
    action: 'Deploy Templates',
    status: 'success',
    message: 'Deployed 3 page templates to WordPress',
    timestamp: '2024-01-20T09:05:00Z',
  },
  {
    id: 'l3',
    project_id: '1',
    action: 'Create Pages',
    status: 'success',
    message: 'Created 9 pages in WordPress successfully',
    timestamp: '2024-01-20T09:15:00Z',
  },
  {
    id: 'l4',
    project_id: '1',
    action: 'Generate Sitemap',
    status: 'success',
    message: 'XML sitemap generated and submitted to Google Search Console',
    timestamp: '2024-01-20T09:20:00Z',
  },
];
